CREATE TABLE IF NOT EXISTS qb_competency_job_snapshot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_platform VARCHAR(32) NOT NULL DEFAULT 'BOSS直聘',
  source_url VARCHAR(500) NOT NULL,
  source_job_key VARCHAR(128) NULL,
  title VARCHAR(255) NOT NULL,
  dimension VARCHAR(64) NOT NULL,
  skill VARCHAR(255) NULL,
  location VARCHAR(128) NULL,
  salary VARCHAR(128) NULL,
  experience VARCHAR(128) NULL,
  education VARCHAR(128) NULL,
  company VARCHAR(255) NULL,
  description VARCHAR(1000) NULL,
  tags_json TEXT NULL,
  source_updated_at DATETIME(3) NULL,
  last_seen_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  availability_status VARCHAR(32) NOT NULL DEFAULT 'active',
  sync_version BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_competency_job_source_url (source_url),
  KEY idx_competency_job_dimension (dimension, availability_status, is_deleted),
  KEY idx_competency_job_source_key (source_job_key),
  KEY idx_competency_job_updated (updated_at, availability_status, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qb_competency_job_sync_record (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trigger_type VARCHAR(32) NOT NULL,
  trigger_by BIGINT UNSIGNED NULL,
  platform VARCHAR(32) NOT NULL DEFAULT 'BOSS直聘',
  status VARCHAR(32) NOT NULL,
  keyword_count INT NOT NULL DEFAULT 0,
  city_count INT NOT NULL DEFAULT 0,
  fetched_candidate_count INT NOT NULL DEFAULT 0,
  success_count INT NOT NULL DEFAULT 0,
  failure_count INT NOT NULL DEFAULT 0,
  offline_count INT NOT NULL DEFAULT 0,
  error_message VARCHAR(1000) NULL,
  started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  is_deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_competency_sync_started (started_at, status, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
